### ISSUE TITLE
Allow Cocinafile DSL to provide/override machine IP addresses

### ISSUE THREAD

**Issue by brandocorp** [brandocorp/cocina#1]
Something like the following:

``` ruby
instance 'web-ubuntu-1404' do
  depends 'app-ubuntu-1404'
  ipaddress '10.10.10.10'
end
```

This would be equivalent to passing in the following in the `.kitchen.yml`

``` yaml
suites:
  - name: web
    driver:
      network:
        - ["private_network", ip: "10.10.10.10"]
```

This would be simple for the `kitchen-vagrant` driver. Need to see how easy it would be for the `kitchen-docker` driver.
